---
title: 'SMML: Exercise 01'
author: "Abhijeet Parida"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

## Exercise 1-6
```
![Alt text] (picture.jpg)
```


## Exercise 7

```{r}
x=seq(-2,2,length.out = 100)
v_max=(1+sqrt(5))/2
v_min=(1-sqrt(5))/2
m=c(v_max,v_min)
plot (x,x*exp(-((x-1)**2)/2), col='red')
abline(v=m)
```

## Exercise 8

```{r}
data("iris")
summary(iris$Sepal.Length)

```
```{r}
summary(iris$Petal.Length)

```
```{r}
summary(iris$Sepal.Width)


```
```{r}
summary(iris$Petal.Width)

```

## Exercise 9
```{r}
## Histogram of Sepal Length default with break
hist(iris$Sepal.Length)
```

```{r}
## Histogram of Sepal Length with break 20
hist(iris$Sepal.Length, breaks = 20)
```

## Exercise 10
```{r}
sertosa=iris$Species==levels(iris$Species)[1]
sertosa_no=iris[sertosa,]$Sepal.Length<5.5
sprintf("%d %s flowers have Sepal Length <5.5, rest %d do  not",sum(sertosa_no),levels(iris$Species)[1],50-sum(sertosa_no))
```
```{r}
virginica=iris$Species==levels(iris$Species)[3]
virginica_no=iris[virginica,]$Sepal.Length<5.5
sprintf("%d %s flowers have Sepal Length <5.5, rest %d do not",sum(virginica_no),levels(iris$Species)[3],50-sum(virginica_no))
```
```{r}
versicolor=iris$Species==levels(iris$Species)[2]
versicolor_no=iris[versicolor,]$Sepal.Length<5.5
sprintf("%d %s flowers have Sepal Length <5.5, rest %d do not",sum(versicolor_no),levels(iris$Species)[2],50-sum(versicolor_no))
```

## Exercise 11
```{r}
pairs(iris, col=iris$Species)
```

## Exercise 12
```{r}
par(mfrow=c(1,3))
plot(iris[sertosa,]$Petal.Width, iris[sertosa,]$Petal.Length, main = 'Sertosa')
plot(iris[virginica,]$Petal.Width, iris[virginica,]$Petal.Length, main = 'Virgnica')
plot(iris[versicolor,]$Petal.Width, iris[versicolor,]$Petal.Length, main = 'Versicolor')

```

## Exercise 13
```{r}
p1= c(-1,-1,0)
p2= c(-1,1,0)
p3= c(1,1,0)
p4= c(1,-1,0)
p5= c(0,0,2)

v = seq(0,1,0.05)

e1 = v %o% (p2-p1) + rep(1,21) %o% p1
e2 = v %o% (p3-p2) + rep(1,21) %o% p2
e3 = v %o% (p4-p3) + rep(1,21) %o% p3
e4 = v %o% (p1-p4) + rep(1,21) %o% p4
e5 = v %o% (p5-p1) + rep(1,21) %o% p1
e6 = v %o% (p5-p2) + rep(1,21) %o% p2
e7 = v %o% (p5-p3) + rep(1,21) %o% p3
e8 = v %o% (p5-p4) + rep(1,21) %o% p4

pyramid = rbind(e1,e2,e3,e4,e5,e6,e7,e8)

projection_matrix <- t(matrix(c(1,0,0,0,1,0), nrow =2, ncol= 3,byrow= TRUE))
pyramid_2D <- pyramid %*% projection_matrix
plot(pyramid_2D[,1],pyramid_2D[,2], type="l")
```
## Exercise 14
```{r}
phi=0.05*pi
theta=0.3*pi

rotate_z<-matrix(c(cos(phi),-sin(phi),0,sin(phi),cos(phi),0,0,0,1), nrow =3, ncol= 3,
                 byrow= TRUE)

rotate_y<-matrix(c(cos(theta), 0, sin(theta), 0, 1, 0, -sin(theta), 0, cos(theta)),
                 nrow =3, ncol= 3, byrow= TRUE)

post_rot_z = pyramid %*% rotate_z %*% projection_matrix
post_rot_y = pyramid %*% rotate_y %*% projection_matrix
par(mfrow=c(1,2))
plot(post_rot_z[,1], post_rot_z[,2],type = "l")
plot(post_rot_y[,1], post_rot_y[,2], type = "l")


```